<table border="1">
	<caption style="text-align: left; padding-bottom: 5px; padding-left: 5px;">
		Projeto: <?php echo $this->projeto->getNomeProjeto(); ?>
	</caption>
	<tr>
		<th style="width: 200px;">Nome Tarefa</th>
		<th style="width: 100px;">Data Início</th>
		<th style="width: 100px;">Hora Início</th>
	</tr>
	<?php
		$arTarefas	= $this->projeto->getTarefas();
		if( $arTarefas->count() > 0 ){
		foreach ( $arTarefas as $tarefa ) {?>
			<tr>
				<td style="text-align: left; padding-left: 5px;" ><?php echo $tarefa->getNomeTarefa(); ?></td>
				<td style="text-align: center;"><?php echo $tarefa->getDataInicio()->format( 'd-m-Y' ); ?></td>
				<td style="text-align: center;"><?php echo $tarefa->getDataInicio()->format( 'H:i:s' ); ?></td>
			</tr>
		<?php } 
		} else { ?>
			<tr>
				<td colspan="3">Nenhuma tarefa encontrada</td>
			</tr>
			
		<?php 
		}
	?>
</table>